mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
context:
    data:
        site_title: Zerocoin
        author:
            name: Ian Miers
            url: "http://hms.isi.jhu.edu/index.php/people/11.html"
            twitter: imichaelmiers
        google_analytics_id: UA-40085231-1
        home_url: index.html
        menu:
            - title: Home
              url: index
            - title: People
              url: people
            - title: software
              url: software
            - title: Q and A
              url: q_and_a
            - title: Research Paper
              url: research_paper
ignore:
   - "*.swp" # ignore gvim swap file
   - "*~"
   - "*.bak"
   - ".git"

publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../../zerocoin.github.io/
        url: git@github.com:Zerocoin/zerocoin.github.io.git

meta:
    nodemeta: meta.yaml
markdown:
    extensions:
        - smartypants
        - toc

urlcleaner:                                                                                                                                                                   
    index_file_names:                                                                                                                                                         
        - index.html                                                                                                                                                          
    strip_extensions:                                                                                                                                                         
        - html                                                                                                                                                                
    append_slash: true 
